#!/usr/bin/env python2
# -*- coding: utf-8 -*-

# blazars from Fan et al. (2016), obtained from the 3FGL telescope at Fermi.


# In[0]: read and parse data; 999 sources with known redshift

import csv

Z = []
with open('asu.tsv') as tsv:
    for line in csv.reader(tsv, delimiter="\t"):
        line = [s.replace(" ", "") for s in line]
        print line
        if len(line) > 2: Z.append(line[1])
    
print Z
